### ISSUE TITLE
AWS Lambda upload?

### ISSUE THREAD

**Issue by chauhanprateek89** [Vadorequest/serverless-ssr-hbs#1]
I am new to AWS development and want to use this in SSR of HTML to PDF and storing them in S3 buckets. How can I do this? Also, how can I upload this to lambda function?

**Comment by Vadorequest** [comment]
This project relies on https://serverless.com/ which is the tool I use to package/upload the source code to AWS lambda.

See https://serverless.com/learn/quick-start/ to get started with the serverless framework.

But I'm not quite sure to follow what you want to do.

**Comment by chauhanprateek89** [comment]
Sorry if I wasn't able to clarify the use case.

- My requirement is that I have a GET API which I will be using to get the data from DynamoDB. 
- Let's say I get 10 variables from DynamoDB, I want these variables to be inserted into handlebar template.
- Once inserted, this HTML file has to be converted into PDF and saved in S3. 
- All this will lie behind API Gateway.
- Once the user clicks 'submit report', whatever values they have filled in the form will first be inserted in DynamoDB table.
- Then the above-mentioned process will start.
- The end product has to be a link of the PDF file stored in S3, that is shown to the user.

**Comment by chauhanprateek89** [comment]
Previously, for some other use-case, I had to use moment.js. 
For that to work in lambda, I had to create a small project on the local environment.
Compiled the project so that 'node_modules' directory can be created at the root of this project.
Then selected all the contents of the root folder, zipped them and uploaded them to Lambda.
In the inline editor of Lambda, I changed the index.js function and started using it.

Now, I know that the size of the above-mentioned project was very small, that's why it was possible to develop the use-case in the inline-editor.
This use-case won't follow the same process. Therefore, I want to ask before zipping and uploading, what all packages I have to install, so that the node-modules dir is created and can be zipped and uploaded to lambda?

**Comment by Vadorequest** [comment]
So, you basically need a HTML page with a form, with inputs for those entries, once submitted you generate a PDF from a handlebars template and you upload this PDF file to a S3 bucket, then you display the generated link back to the user.

This is doable with the serverless framework indeed. I suggest you do the getting started and see if it fits your needs.

This project's goal is to display HTML content provided through SSR based on HBS templates.
You don't need SSR in your case, it's optional. (ou could use a SPA for the form, for instance, or SSR, it's up to you)

Your needs seem to match what Serverless has to offer, so I suggest you dig into it, you'll find everything you need to know about packaging for AWS. If I had to do what you want to do, I'd have:

- A lambda that serves a HTML page with the form (I'd use this package, serverless-ssr-hbs because of its simplicity).
- A lambda that process the form's values, generates a PDF file, then upload it to S3 and return the generated S3 file path. (Ajax ? Most likely)

**Comment by chauhanprateek89** [comment]
Thanks a lot for your help. You last two points are going to help for sure because the first point has already been implemented. That means I was heading in the right direction.
Thank you once again.
